name: "setup-catwalk"
description: "Setup catppuccin/catwalk"
author: "Catppuccin Org"

inputs:
  catwalk-version:
    description: "Semver compatible version of catppuccin/catwalk to install"
  github-token:
    description: "GitHub token to use for authentication when installing catppuccin/catwalk"
    required: false
    default: ${{ github.token }}

runs:
  using: "composite"
  steps:
    - uses: sgoudham/setup-crate@feat/support-unzipped-binaries-diverged
      with:
        repo: catppuccin/catwalk@${{ inputs.catwalk-version }}
        github-token: ${{ inputs.github-token }}

branding:
  icon: "dollar-sign"
  color: "yellow"
